name: 02 - Workflow Events

on: push

jobs:
    echo:
        runs-on: ububtu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggeref by a(n) ${{github.event_name}}"
