name: 04 - Using Actions - Windows

on: workflow_dispatch

jobs:
    build:
        runs-on: windows-latest
        
        #defaults:
        #    run:
        #        working-directory: .\temp\code
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      novifile.txt
                  sparse-checkout-cone-mode: false
            - name: Printing Folders
              run: |
                  dir
                  type novifile.txt
                  #type README.md
